# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.CharField(max_length=128)),
                ('lms_callback_url', models.CharField(db_index=True, max_length=128)),
                ('queue_name', models.CharField(db_index=True, max_length=128)),
                ('xqueue_header', models.CharField(max_length=1024)),
                ('xqueue_body', models.TextField()),
                ('s3_keys', models.CharField(max_length=1024)),
                ('s3_urls', models.CharField(max_length=1024)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('pull_time', models.DateTimeField(blank=True, null=True)),
                ('push_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('grader_id', models.CharField(max_length=128)),
                ('pullkey', models.CharField(max_length=128)),
                ('grader_reply', models.TextField()),
                ('num_failures', models.IntegerField(default=0)),
                ('lms_ack', models.BooleanField(default=False)),
                ('retired', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='submission',
            index_together=set([('queue_name', 'retired', 'pull_time', 'arrival_time'), ('lms_callback_url', 'retired'), ('queue_name', 'retired', 'push_time', 'arrival_time')]),
        ),
    ]
